### ISSUE TITLE
Binary contains reference to build directory

### ISSUE THREAD

**Issue by HaleTom** [robert7/nixnote2#31]
```
% pwd
/home/ravi/code/aur/nixnote2-git
% strings -a pkg/nixnote2/usr/bin/nixnote21 | grep $PWD
/home/ravi/code/aur/nixnote2-git/src/nixnote2/../libs/lib
% 
```

I think the culprit is:

```
src/nixnote2/NixNote21.pro
9:    QMAKE_RPATHDIR += $$PWD/../libs/lib
```

Have you looked at [`absolute_path`](http://doc.qt.io/qt-5/qmake-function-reference.html#absolute-path-path-base)?

**Comment by robert7** [comment]
I don't have enough time now. I'll check in more details later. But I think, this may have been already resolved. You are using old version (v2.1.0-beta3). Pls try with the last tag "v2.1.0-beta4g"

E.g. the QMAKE_RPATHDIR" is not anymore part of the project (it is expected to come from outside of the project).
Also see end of this issue: https://github.com/robert7/nixnote2/issues/20 for explanation. 

But the solution with "html-tidy" is not yet the final one. I plan to improve.

**Comment by HaleTom** [comment]
Sorry, not resolved:

```
==> Finished making: nixnote2-git 2.1.0.beta4g-1 (Sat 06 Oct 2018 20:45:56 +07)
nixnote2-git E: Dependency hunspell detected and not included (libraries ['usr/lib/libhunspell-1.6.so.0'] needed in files ['usr/bin/nixnote2'])
nixnote2-git E: Insecure RPATH '/home/ravi/code/aur/nixnote2-git/src/nixnote2/../libs/lib' in file ('usr/bin/nixnote21')
```

Did you start linking to `hunspell` again?  It wasn't flagged as a dependency in `beta-3`.

**Comment by HaleTom** [comment]
I couldn't find any directory called `libs`. 

If it's related to `tidy`, perhaps install it and specify the expected installed location instead.

Any reason it's not `/usr/lib/nixnote2/tidy`?

**Comment by HaleTom** [comment]
Please let me know when you next update `continuous` as I may then be able to close a few issues.

**Comment by robert7** [comment]
>Can you confirm that the external dependency on hunspell is new between beta-3 and beta4g?

Yes it is new. See this issue for details: https://github.com/robert7/nixnote2/issues/25

>Please let me know when you next update continuous as I may then be able to close a few issues.

Yes. I'll do. I think, if you follow the repository, you should get notification about "continuous" build..

>../libs/lib

I'll check. Sorry, I'm bit busy now. 

"../libs/lib" its coming  **outside** of the project. So it must be in your config. 

Check e.g. the Travis build script: https://github.com/robert7/nixnote2/blob/master/.travis.yml
there is no "../libs/lib" there **at all** :)

**Comment by robert7** [comment]
>Any reason it's not /usr/lib/nixnote2/tidy

I want to change it like this. Just need a bit time :)

But in your packaging, you can already today to it like this. the path to tidy is given a param to he build script. So you can do a packaging already **today** with tidy in "/usr/lib/nixnote2/tidy"

**Comment by robert7** [comment]
so I verified: there is no relative path in the binaryx (except you feed it to the project from outside)
![screen_20181009_03](https://user-images.githubusercontent.com/1135218/46693532-59046680-cc0a-11e8-86a7-b332d9ab3970.png)

**Comment by HaleTom** [comment]
Thank you - I'm not getting that warning message anymore either.
