### ISSUE TITLE
Font size issue in search bar and when switching to wide/narrow note list

### ISSUE THREAD

**Issue by neilwarrack** [robert7/nixnote2#44]
When switching to wide note list from narrow note list in preferences (or to narrow from wide) the font size stays at the correct (non-'system default') value, but the rows themselves seem to appear too small (probably at the size capable of handling the system default). The result is text that cannot be read due to being larger than the area it appear in. 
BEFORE PROBLEM AND AFTER SOLUTION:
![before](https://user-images.githubusercontent.com/32457242/46959834-47eda680-d09d-11e8-8940-e73444461360.png)
DURING:
![after](https://user-images.githubusercontent.com/32457242/46959860-5b007680-d09d-11e8-9e42-bd8e7d025771.png)

Solution:
To get rid of it you can just click on a notebook title in the side left panel, but if you do not have 'show left panel' selected from the View menu then it's not clear how to get it looking good.

The search bar is also not at the GUI or editor font size. I have the editor and GUI font size set to 20 because otherwise the entire app is unreadable (test is too small). on my higher def screen.

Version: 2.1.0-beta4j 201810131046 ubuntu16.04.1

PS - I like the new logo - but I will miss the linux penguin logo - thanks for developing!
Edit1 - some explanations of the images.
Edit2 - some removal of template formatting

**Comment by robert7** [comment]
Should be fixed in "2.1.0-beta4k" pls retest with the new development build (should be available in a while).

**Comment by neilwarrack** [comment]
I cannot get the 2.1.0-beta4k build. I did:
sudo add-apt-repository ppa:nixnote/nixnote2-stable -y -u
sudo apt install nixnote2 -y
...and I still get, "nixnote2 is already the newest version (2.1.0-beta4j~201810131046~ubuntu16.04.1)."
I tried sudo apt update and upgrade too.

**Comment by robert7** [comment]
yes. the PPA only has the "last stable version"
to test the "dev" version - you need to use AppImage build https://github.com/robert7/nixnote2/releases/tag/continuous-develop

but its easy:
* quit the PPA version
* download the AppImage, mark as executable
* run - it will use the same config/data you have for PPA version
* after you finished testing, you can simly quit the AppImage version & eventually delete it or you can continue using it, until the updates get to the stable version (which is provided as AppImage and as PPA)
More info here: https://github.com/robert7/nixnote2/wiki/Releases---versions%2C-build-pipeline%2C-branches%2C-tags

**Comment by robert7** [comment]
:) i wrota a wiki page https://github.com/robert7/nixnote2/wiki/HowTo---Test-latest-application-changes-using-development-version

**Comment by arkenoi** [comment]
The problem persists in 2.1.3

![Screenshot from 2019-06-06 19-31-07](https://user-images.githubusercontent.com/6000406/59050027-0317b980-8892-11e9-927e-390f8ffdfea0.png)

**Comment by robert7** [comment]
hmm... it works for me..
![screen_20190606_01](https://user-images.githubusercontent.com/1135218/59050978-158ef480-888c-11e9-9fb4-600e020ab935.png)

![screen_20190606_02](https://user-images.githubusercontent.com/1135218/59050983-19227b80-888c-11e9-8666-f9f0b78486fa.png)

**Comment by arkenoi** [comment]
I have 150dpi display and my fonts are adjusted accordingly. May be related somehow..

**Comment by arkenoi** [comment]
Nope! Actually the reason is simple: if a text is wrapped it gets ugly. You do not have any wrapped titles and that's why it all looks ok ;-)

**Comment by robert7** [comment]
Hm I don't get any wrapped titles even if the column is narrow (I get ellipsis or cut (in date field)).
What version are you using (and what packaging? it could be Qt issue...)

![screen_20190607_02](https://user-images.githubusercontent.com/1135218/59082930-861e2b80-88f5-11e9-8c3b-6deafee56741.png)

**Comment by arkenoi** [comment]
2.1.3, fedora packaging.
